---
- name: add repository key
  apt_key: 
    keyserver: hkp://pgp.mit.edu:80
    id: 58118E89F3A912897C070ADBF76221572C52609D
    state: present
  sudo: yes
  when: ansible_os_family == 'Debian'

- name: add repository
  apt_repository: repo='deb https://apt.dockerproject.org/repo debian-jessie main' state=present update_cache=yes
  sudo: yes
  when: ansible_os_family == 'Debian'

- name: install apt-transport-https
  apt: name=apt-transport-https state=present update_cache=yes
  sudo: yes
  when: ansible_os_family == 'Debian'

- name: install
  apt: name=docker-engine state=present update_cache=yes
  notify: start and enable
  sudo: yes
  when: ansible_os_family == 'Debian'